
import "./globals.css";

import { ClerkProvider } from "@clerk/nextjs";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/header";
import { dark } from "@clerk/themes";

const inter = Inter({ subsets: ['latin'] }); // ✅ correct spelling



export const metadata = {
  title: "NextStepAI-AI Career Coach",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <ClerkProvider appearance={{
      baseTheme:dark,
    }}
    
    >
    <html lang="en" suppressHydrationWarning >
      <body className={`${inter.className} antialiased`}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            {/* Header*/}
            <Header/>
            <main className="min-h-screen">{children}</main>
            {/*Footer*/}
            <footer className="bg-muted/50 py-12">
              <div className="container mx-auto px-4 text-center text-gray-200 ">
                 <p>Made with ❤️ by Shivansh Singh</p>
              </div>

            </footer>
            
            
          </ThemeProvider>
        
      </body>
    </html>
    </ClerkProvider>
  );

}
